# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHub'
          repository: 'w10-ltsc2016-vs16'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
