name: Windows image build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/windows-ltsc2016-vs2019:latest
